services:
  web:
    build: ./frontend/
    container_name: adventurelog-frontend-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "${FRONTEND_PORT:-8015}:3000"
    depends_on:
      - server

  db:
    image: postgis/postgis:16-3.5
    container_name: adventurelog-db-dev
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/

  server:
    build: ./backend/
    container_name: adventurelog-backend-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "${BACKEND_PORT:-8016}:80"
    depends_on:
      - db
    volumes:
      - adventurelog_media_dev:/code/media/

volumes:
  postgres_data_dev:
  adventurelog_media_dev:
